In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv("../data/FreshFood.csv")
df = df[df["protein_per_100g"].notna()]
df.head()

,tpnc,title,brand,price_actual,price_unit_price,price_unit_of_measure,price_per_kg,price_per_kg_unit,protein_per_100g,protein_units,category
0,302328940,"Yoplait Frubes Yoghurt Tubes - Strawberry, Red...",FRUBES,2.10,6.31,kg,6.31,kg,3.8,per 100g,Fresh Food
1,285021202,Petits Filous Strawberry Raspberry & Apricot K...,Yoplait,3.50,4.14,kg,4.14,kg,5.4,per 100g,Fresh Food
2,312351579,Cathedral City Plant Based Mature Cheddar Chee...,CATHEDRAL CITY,2.00,13.33,kg,13.33,kg,0.2,per 100g,Fresh Food
3,290920510,Tesco British Salted Block Butter 250G,TESCO,1.99,7.96,kg,7.96,kg,0.6,per 100g,Fresh Food
4,290921181,Tesco British Unsalted Butter 250G,TESCO,1.99,7.96,kg,7.96,kg,0.6,per 100g,Fresh Food

In [20]:
df.count()

tpnc                     4288
title                    4288
brand                    4288
price_actual             4288
price_unit_price         4288
price_unit_of_measure    4288
price_per_kg             4288
price_per_kg_unit        4288
protein_per_100g         4288
protein_units            4288
category                 4288
dtype: int64

In [21]:
print(df["protein_units"].unique())
print(df["price_unit_of_measure"].unique())
print(df["price_per_kg_unit"].unique())

['per 100g']
['kg' 'litre' 'each' 'kg DR.WT' '100g' 'litre DR.WT']
['kg' 'litre' 'each' 'kg dr.wt' 'litre dr.wt']

In [25]:
filtered_df = df[df["price_unit_of_measure"] != "each"]
filtered_df["protein_per_pound"] = 10 * filtered_df["protein_per_100g"] / filtered_df["price_per_kg"] 
filtered_df.sort_values("protein_per_pound", ascending=False).head(50)

/var/folders/73/rvwyvc7n3lzdfxn3pnvhwpn80000gn/T/ipykernel_64670/409227937.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["protein_per_pound"] = 10 * filtered_df["protein_per_100g"] / filtered_df["price_per_kg"]

,tpnc,title,brand,price_actual,price_unit_price,price_unit_of_measure,price_per_kg,price_per_kg_unit,protein_per_100g,protein_units,category,protein_per_pound
3928,312709342,Tesco Finest Bourbon Pulled Beef With Creamy M...,TESCO finest,4.50,0.01,kg,0.01,kg,7.5,per 100g,Fresh Food,7500.000000
1025,285210344,Tesco British Chicken Drumsticks 1Kg,TESCO,2.15,2.15,kg,2.15,kg,19.0,per 100g,Fresh Food,88.372093
1837,306820961,Tesco Chicken Drumsticks 2Kg,TESCO,4.30,2.15,kg,2.15,kg,19.0,per 100g,Fresh Food,88.372093
4133,320685155,Tesco Chicken Wings 1KG,TESCO,2.19,2.19,kg,2.19,kg,19.1,per 100g,Fresh Food,87.214612
550,285210436,Tesco British Chicken Legs 1Kg,TESCO,2.25,2.25,kg,2.25,kg,18.1,per 100g,Fresh Food,80.444444
1253,258016074,Tesco British Sliced Pork Liver,TESCO,3.40,3.40,kg,3.40,kg,26.8,per 100g,Fresh Food,78.823529
4441,321222903,For Goodness Shakes Protein Strawberry Shake 4...,FOR GOODNESS SHAKE,3.00,6.37,litre,6.37,litre,50.0,per 100g,Fresh Food,78.492936
30,313165959,Tesco All Rounder Potatoes 2Kg,TESCO,1.32,0.66,kg,0.66,kg,4.5,per 100g,Fresh Food,68.181818
389,306820039,Tesco Chicken Thighs 2Kg,TESCO,5.50,2.75,kg,2.75,kg,18.5,per 100g,Fresh Food,67.272727
2895,321103768,Tesco Extra Large Whole Chicken 2.1-2.6kg,TESCO,6.35,3.02,kg,3.02,kg,20.0,per 100g,Fresh Food,66.225166
2896,321046461,Tesco Large Whole Chicken 1.7-2.1kg,TESCO,5.15,3.03,kg,3.03,kg,20.0,per 100g,Fresh Food,66.006601
2899,320672285,Tesco Medium Whole Chicken 1.3-1.7kg,TESCO,3.95,3.04,kg,3.04,kg,20.0,per 100g,Fresh Food,65.789474
3999,322430488,The Gym Kitchen Chipotle Chicken & Rice 500g,THE GYM KITCHEN,4.75,9.50,kg,9.50,kg,59.0,per 100g,Fresh Food,62.105263
352,285210396,Tesco British Chicken Thighs 1Kg,TESCO,2.99,2.99,kg,2.99,kg,18.5,per 100g,Fresh Food,61.872910
2867,322637492,Tesco Slower Grown Chicken Drumsticks 600g,TESCO,1.85,3.08,kg,3.08,kg,18.8,per 100g,Fresh Food,61.038961
831,284953900,Tesco Roast In Bag Ready Basted Whole Chicken ...,TESCO,7.00,4.67,kg,4.67,kg,24.9,per 100g,Fresh Food,53.319058
1306,256056991,Tesco Roasted Monkey Nuts 250G,TESCO,1.35,5.40,kg,5.40,kg,28.2,per 100g,Fresh Food,52.222222
153,299914291,Creamfields Skimmed UHT Milk 1L,CREAMFIELDS,0.69,0.69,litre,0.69,litre,3.6,per 100g,Fresh Food,52.173913
216,299914279,Creamfields Semi Skimmed UHT Milk 1L,CREAMFIELDS,0.69,0.69,litre,0.69,litre,3.6,per 100g,Fresh Food,52.173913
1010,307758273,Tesco Gingerbread Biscuit,TESCO,1.20,1.20,kg,1.20,kg,6.1,per 100g,Fresh Food,50.833333
997,306941570,Tesco Roast In The Bag Rotisserie Style Whole ...,TESCO,7.00,4.67,kg,4.67,kg,23.4,per 100g,Fresh Food,50.107066
3367,313748760,Tesco British Turkey Drumsticks,TESCO,4.00,4.00,kg,4.00,kg,19.8,per 100g,Fresh Food,49.500000
3416,313748760,Tesco British Turkey Drumsticks,TESCO,4.00,4.00,kg,4.00,kg,19.8,per 100g,Fresh Food,49.500000
9,254656543,"Tesco British Semi Skimmed Milk 2.272L, 4 Pints",TESCO,1.65,0.73,litre,0.73,litre,3.6,per 100g,Fresh Food,49.315068
7,254656508,"Tesco British Skimmed Milk 2.272L, 4 Pints",TESCO,1.65,0.73,litre,0.73,litre,3.6,per 100g,Fresh Food,49.315068
800,275455524,Tesco Roast In Bag Butter Basted Whole Chicken...,TESCO,7.00,4.67,kg,4.67,kg,22.5,per 100g,Fresh Food,48.179872
1185,275461706,"Tesco Roast In The Bag Pork, Sage & Onion Stuf...",TESCO,7.00,4.67,kg,4.67,kg,22.5,per 100g,Fresh Food,48.179872
18,254656399,"Tesco British Whole Milk 2.272L, 4 Pints",TESCO,1.65,0.73,litre,0.73,litre,3.5,per 100g,Fresh Food,47.945205
3679,322242808,Whitworths Monkey Nuts 280g,whitworths,2.10,7.50,kg,7.50,kg,34.6,per 100g,Fresh Food,46.133333
2822,314315568,Creamfields Mild Cheddar 900g,CREAMFIELDS,4.99,5.54,kg,5.54,kg,25.4,per 100g,Fresh Food,45.848375
3501,322150370,Tesco Garlic & Herb Spatchcock 1.5kg,TESCO,7.00,4.67,kg,4.67,kg,21.4,per 100g,Fresh Food,45.824411
403,302676629,Creamfields Lighter Mature Cheese 400G,CREAMFIELDS,2.49,6.22,kg,6.22,kg,27.9,per 100g,Fresh Food,44.855305
448,299970292,Creamfields Low Fat Natural Yogurt 500G,CREAMFIELDS,0.55,1.10,kg,1.10,kg,4.9,per 100g,Fresh Food,44.545455
763,252995167,Tesco 8 Reduced Fat Pork Sausages 454G,TESCO,1.79,3.94,kg,3.94,kg,17.5,per 100g,Fresh Food,44.416244
930,299669459,Tesco Reduced Fat Cumberland Sausage 454G,TESCO,1.79,3.94,kg,3.94,kg,16.8,per 100g,Fresh Food,42.639594
918,258016016,Tesco Lamb Sliced Liver,TESCO,6.15,6.15,kg,6.15,kg,25.8,per 100g,Fresh Food,41.951220
190,292312017,Woodside Farms Unsmoked Back Bacon 300G,WOODSIDE FARMS,1.25,4.17,kg,4.17,kg,17.4,per 100g,Fresh Food,41.726619
166,292311836,Woodside Farms Smoked Back Bacon 300G,WOODSIDE FARMS,1.25,4.17,kg,4.17,kg,17.4,per 100g,Fresh Food,41.726619
240,310681024,Creamfields Grated Cheddar 500G,CREAMFIELDS,2.99,5.98,kg,5.98,kg,24.9,per 100g,Fresh Food,41.638796
207,302676607,Creamfields Mature White Cheddar 400G,CREAMFIELDS,2.49,6.22,kg,6.22,kg,25.4,per 100g,Fresh Food,40.836013
465,302676567,Creamfields Mild White Cheddar 400G,CREAMFIELDS,2.49,6.22,kg,6.22,kg,25.4,per 100g,Fresh Food,40.836013
4081,320816358,Tesco Fire Pit Sweet and Smoky BBQ Chicken Dru...,FIRE PIT,5.25,5.83,kg,5.83,kg,23.8,per 100g,Fresh Food,40.823328
294,258431866,Tesco Lean Pork Mince 5% Fat 500g,TESCO,2.55,5.10,kg,5.10,kg,20.5,per 100g,Fresh Food,40.196078
344,302676688,Creamfields Red Leicester Cheese 400G,CREAMFIELDS,2.49,6.22,kg,6.22,kg,25.0,per 100g,Fresh Food,40.192926
229,299970378,Creamfields Apricot Strawberry Raspberry Froma...,CREAMFIELDS,0.89,1.48,kg,1.48,kg,5.9,per 100g,Fresh Food,39.864865
929,261878876,Tesco British Lincolnshire Sausages 8 Pack 454G,TESCO,1.79,3.94,kg,3.94,kg,15.7,per 100g,Fresh Food,39.847716
2337,264429037,Tesco Firepit Chinese Chicken Style Thighs 900G,FIRE PIT,5.25,5.83,kg,5.83,kg,22.9,per 100g,Fresh Food,39.279588
4251,322344037,Hearty Food Co. Single Garlic Baguette 165g,HEARTY FOOD CO.,0.35,2.12,kg,2.12,kg,8.3,per 100g,Fresh Food,39.150943
957,262615661,Tesco British Cumberland Sausages 12 Pack 681G,TESCO,2.65,3.89,kg,3.89,kg,15.0,per 100g,Fresh Food,38.560411
2327,309173667,Tesco Mature Cheddar 700G,TESCO,4.65,6.64,kg,6.64,kg,25.4,per 100g,Fresh Food,38.253012